openapi: 3.0.1
info:
  title: node-backend
  description: My cool app
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification
paths:
  /unavailableDates:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Return the example with the specified id
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Example'
        4XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Example not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    # post:
    #   tags:
    #     - Examples
    #   description: Create a new example
    #   requestBody:
    #     description: an example
    #     content:
    #       application/json:
    #         schema:
    #           $ref: '#/components/schemas/ExampleBody'
    #     required: true
    #   responses:
    #     201:
    #       description: Return the example with the specified id
    #       content:
    #         application/json:
    #           schema:
    #             $ref: '#/components/schemas/Example'
    #     4XX:
    #       description: Example not found
    #       content:
    #         application/json:
    #           schema:
    #             $ref: '#/components/schemas/Error'
    #     5XX:
    #       description: Example not found
    #       content:
    #         application/json:
    #           schema:
    #             $ref: '#/components/schemas/Error'
 
  /unavailableDates/{month}:
    get:
      tags:
        - Examples
      parameters:
        - name: month
          in: path
          description: The month of the dates to retrieve
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Return the example with the specified month
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Example'
        4XX:
          description: Month not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        5XX:
          description: Month not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
 
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    Example:
      type: object
      properties:
        id:
          type: integer
          example: 3
        name:
          type: string
          example: example 3
    Error:
      type: object
      additionalProperties: true

    ExampleBody:
      title: example
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: no_stress
